name: debt-reduction-planner
proxy:
  node:
    - debt-reduction-planner.lndo.site:8080
services:
  node:
    type: node:14
    globals:
      '@vue/cli': latest
      '@vue/cli-service-global': latest
    build:
     - npm install
    command: npm run serve
tooling:
  npm:
    service: node
  vue:
    service: node
